name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Prat33k18
          outputs: dist/snake.svg
      - name: Upload Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/snake.svg
      - name: Commit and Push Snake Animation
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add dist/snake.svg
          git commit -m 'Generated snake animation'
          git push
